import '../models/material_master_item.dart';
import '../models/survey_options.dart';

/// DEV-ONLY seed data for material_master_items — see
/// [seedMaterialMasterItems] in material_master_seed.dart, which inserts
/// this list on fresh installs only.
///
/// These rows mirror the placeholder rows already present in the
/// live Supabase material_master_items table (fetched 2026-07-04) — bulk-inserted
/// directly into Postgres with a different casing/vocabulary convention than
/// this app's Dart enums use (e.g. 'FIXED' / 'DN25' / 'Wired' instead of the
/// app's 'fixed' / 'dn25' / 'wired'). Every enum-like field here has been
/// normalized to this app's actual enum names so the row mapper
/// (_materialMasterItemFromRow) decodes them correctly — left as raw text,
/// every one of these fields would silently fall back to null/default.
///
/// Group B's original 24 rows (legacy Duct LoRa/cable catalog) were removed
/// from this seed once group B became a fully manual entry group — a new
/// group B catalog will be imported later; this seed must not recreate the
/// old one on a fresh install (it would also get pushed straight back to
/// Supabase on next sync, undoing a deliberate remote delete of those rows).
///
/// Ids are preserved from the live Supabase rows, so if a developer's fresh
/// local install ever syncs (push-only, see SyncService.pushAll), it upserts
/// onto the SAME remote rows rather than creating duplicates.
///
/// DELETE THIS FILE, material_master_seed.dart, and the single call to
/// seedMaterialMasterItems() in app_database.dart's onCreate once real
/// production Material Master data replaces this placeholder set.
const List<MaterialMasterItem> kMaterialMasterSeedData = [
  MaterialMasterItem(
    id: '22a0e98f-5f4e-4dc8-ac05-0801d55b089f',
    group: MaterialGroup.a,
    materialName: 'DCU',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '058309c6-84c6-4535-aa56-84687e93fe78',
    group: MaterialGroup.a,
    materialName: 'Duct Lora',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '6b51866f-9833-48d7-8727-42a259bf40e7',
    group: MaterialGroup.a,
    materialName: 'Gateway',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '647f0ccc-0929-4926-b4a4-bb49b30f528c',
    group: MaterialGroup.a,
    materialName: 'S2S Cables 3.5M',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '94a4dc24-3419-46a7-a5d6-98df3224fbb2',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN100',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '976bb194-0b7d-4c97-a48a-9ca4ea2c6477',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN100MM',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '246c520f-5960-4e13-bda1-bc8748a15937',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c3ff14b2-22c9-4f0c-8635-bf50bee3739e',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '3040197d-ba00-462c-bf44-627ff0fbf365',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'cb954fe6-e946-441f-a626-4bbd904295a8',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'a2af9980-c65e-499b-97ca-44d6d32e7870',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '5df73f4f-27d6-43c8-b903-a972ee55409f',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN25',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: 'ee108b9b-9f65-47db-9de3-0c4dc743ad25',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN40mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 3,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '852bdcb9-92fc-43ba-85ab-84dd0e119a5a',
    group: MaterialGroup.a,
    materialName: 'Total Sensor UFS DN50mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: 'e723b5e7-dc31-495a-b283-e668f1288f83',
    group: MaterialGroup.c,
    materialName: 'Bolt & Nut GI',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 8,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '62394c2f-861a-434f-8f2a-26b9afd014a1',
    group: MaterialGroup.c,
    materialName: 'Flange Cpvc',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'f4072cf8-da0e-45ad-b3f8-8315ae9d469c',
    group: MaterialGroup.c,
    materialName: 'Flange Cpvc 100mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '963554c3-31cc-4d8d-8776-395d265dafbc',
    group: MaterialGroup.c,
    materialName: 'Flange GI 65mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 4,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '2e2d2aad-8d4f-4c68-af1e-d3ab1e6ac849',
    group: MaterialGroup.c,
    materialName: 'Flange UPVC 100mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c9cfcb8d-d9ae-42a3-92c9-12a8848ea38a',
    group: MaterialGroup.c,
    materialName: 'FTA Cpvc 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 2,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: 'f42d97f7-6ba9-434c-8679-048b2a1841a2',
    group: MaterialGroup.c,
    materialName: 'FTA Cpvc 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '6ce9aee4-a7b3-43c5-908a-fc3e26083e74',
    group: MaterialGroup.c,
    materialName: 'FTA Cpvc 50mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 6,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '4fe16df3-58b7-4d75-ad3d-b467f203caeb',
    group: MaterialGroup.c,
    materialName: 'FTA GI 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'ffac47d0-6ebd-4ffe-82b4-c7e2b76eb928',
    group: MaterialGroup.c,
    materialName: 'FTA GI 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'dfd27644-3823-4072-b1af-546592fcd88d',
    group: MaterialGroup.c,
    materialName: 'FTA GI 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '42450f6c-44e2-473a-b2a1-99bfda25cded',
    group: MaterialGroup.c,
    materialName: 'FTA GI 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '7bc3d1c0-60b6-4120-b40c-ccd3686f959f',
    group: MaterialGroup.c,
    materialName: 'Gasket',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 2,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '4a70b999-44ed-4b39-a1d7-c558061693bd',
    group: MaterialGroup.c,
    materialName: 'Net bult Cpvc',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '1f4bf032-9f4f-4d29-b5e9-c4990301a8e8',
    group: MaterialGroup.c,
    materialName: 'Plumbing Elbow Upvc 100mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '06db784c-2df5-40a5-a10b-27f5e2fc9ce2',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush Cpvc',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '8c51a61e-4a3a-4cd8-beb2-bddeba16ff9e',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush Cpvc 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '17abe610-fb3f-439a-931b-b0c5025fbe04',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush Cpvc 50mmx65mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '22bb5a8f-0d46-4bcf-8ced-46fb387c4696',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush GI 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e753d8f1-db9d-4aee-ac52-2dcf94728988',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush GI 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '50d813b0-9bab-4521-9ee9-0e91130a8f57',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush GI 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '5e105322-cf4d-4f9e-b58a-5c9c82832cf2',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush GI 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'b250e148-c943-4412-9ce4-70478e878298',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush GI 25mmx20mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '07fa2765-a87b-4f50-ab09-f886eecaef4c',
    group: MaterialGroup.c,
    materialName: 'Reducer  bush Upvc 80m*100m',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'be88eb34-459a-4eca-8228-258245d327c8',
    group: MaterialGroup.c,
    materialName: 'Solution Cpvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '42dc4e96-2aea-4b84-aaec-7d765c26c7ae',
    group: MaterialGroup.c,
    materialName: 'Solution Cpvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '1a4c3d1c-be78-401a-90c2-486cd342815c',
    group: MaterialGroup.c,
    materialName: 'Solution Cpvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'bb801079-5cea-42d0-8e6f-fa4851d6201e',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '948702e9-e202-4ef6-b17e-b489e7aed0ae',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e1587233-3f3d-4ce9-a6b1-032a929667b9',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c018f769-3ab6-41fb-908f-cca9b0dfb2bc',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'bf444ec2-325a-4452-94fc-917651c57bec',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'cfebbaee-4129-44d6-94a6-23c7fd49f459',
    group: MaterialGroup.c,
    materialName: 'Solution Upvc 250ml',
    sku: '',
    unit: 'Tins',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'f8598379-8a46-48f2-998b-cd2f2097dbac',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'f474225a-e78c-499f-941c-fe7ccd1d0dc4',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '0dfa96a5-4441-4f4b-9848-341276facb79',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c9ad1fa2-bf43-4671-a7db-6d1aa1fd542b',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '6430c174-fd3a-41ee-b29e-6e83467f6a00',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '3c68837d-e125-4e34-9a03-e1ec3436c55f',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'be7eb452-c10c-4e21-add5-5b167cadf7fa',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '89858fbf-cd89-4250-8bf2-06419be50eb1',
    group: MaterialGroup.c,
    materialName: 'Teflon',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'fd5d05bd-8a55-4941-a2e5-02407c58d238',
    group: MaterialGroup.c,
    materialName: 'Union Cpvc 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 2,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '2452e7cd-1309-444d-b46b-d9c99fb96e34',
    group: MaterialGroup.c,
    materialName: 'Union Cpvc 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '747050d5-468e-47a3-9880-3db4ecc33d97',
    group: MaterialGroup.c,
    materialName: 'Union Cpvc 40mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 6,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: '',
  ),
  MaterialMasterItem(
    id: '32259f29-3b7a-4cbf-a6e7-a6729568aa72',
    group: MaterialGroup.c,
    materialName: 'Union UPVC 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'ec282353-8af1-4405-be53-7810127773bf',
    group: MaterialGroup.c,
    materialName: 'Union UPVC 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '8143752e-f0dc-4cdf-9e2e-212d8b8640d8',
    group: MaterialGroup.c,
    materialName: 'Union UPVC 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '8a3163b6-d5a1-417d-8b7d-ad00dde4d56a',
    group: MaterialGroup.c,
    materialName: 'Union UPVC 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c60110c2-1766-4cec-b2d0-9a30e9598f15',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e3d4660f-5581-4203-81d4-1d6e89d5fb0d',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '20ad3115-2cf2-4819-acd2-58eaf27f468d',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '50f871c1-776a-4c6b-975f-cf5e97696313',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'f4980696-cfe5-4299-9a64-c8741449b7ba',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '1135e695-b75e-4514-be28-1cd88441975f',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'ab1c6176-d25d-456f-a1d3-f91ff05f6cc4',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '85464477-e70e-430f-b4da-6aa458c29806',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '818690cf-7614-4a00-8382-4aac3e9d08ef',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '84583029-1bac-4517-be30-e36ef050d0c3',
    group: MaterialGroup.f,
    materialName: 'Fixer',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '83f3fc07-1830-4fdb-b4f7-7407607bbdbc',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '58ba686b-ea30-4a1b-8c4d-583cbbace07b',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '3a893413-6183-496d-83b2-29ceeef22d1b',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '95f93957-0e1d-4550-93c6-cba0c3c1ec46',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '4237b486-482f-4991-9b4e-79af3592249f',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '46df027f-51d1-45ca-aec5-17dcca87ba00',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'fac43691-2742-4b1e-ab5b-0fbe7099c1a9',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'cead6627-dbf8-44ca-9bbc-aed57311fb7c',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '26b58573-e985-493a-af1d-b93202b8de44',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '7d83cd2e-2caf-442f-acff-1b65a7995f19',
    group: MaterialGroup.f,
    materialName: 'Hacksaw Blade',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '29ba0fe8-033f-4a9b-822f-0b52cba65450',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '4994c6a4-8ea3-446b-b679-079522ee2113',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '6aa83dc5-d90e-4f22-9204-48744aed2897',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e9e71f97-c36e-4d17-8bdb-4bf5544f9a06',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e4226be5-ccdd-4811-a647-d49803812faf',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '423a09da-e99e-441a-b3af-2abc901e7cce',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'b3bce9d4-2de0-4a18-9de2-9cf6e2d9704d',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'd51019c1-3e75-4425-9f46-c50808321009',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '16673f70-d278-44b0-8011-969e6895ae46',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'd50c4734-e0d1-4f86-9ad5-7589175b4894',
    group: MaterialGroup.f,
    materialName: 'Metallic Cable Tie',
    sku: '',
    unit: 'Packet',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c48cb94f-483e-4784-ad8b-a160af9e9359',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '3892ab2f-4d2b-4032-b41d-6b8652912f24',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '6597d753-9651-428f-8b62-b7583c1db1ef',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'aef9369e-7b4c-4ba7-a21b-a9d95f22e4ca',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c0d41239-ba09-41fb-ad64-262b4181ce3f',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'ae238427-7fc6-4734-b0a3-2e9ab794dc31',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '4f504720-1dbb-4181-940a-6ebdb7e5be37',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '7fbf5d89-7177-4a7d-8d74-3ee422927592',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '27a88cc5-071b-42da-bc2b-0a7910e06c10',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'b97796a5-3595-46e2-b30b-ad6031497c27',
    group: MaterialGroup.f,
    materialName: 'Saddle Clamp 25mm',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '2f3c8631-63d2-4477-8267-30ce4b205bff',
    group: MaterialGroup.f,
    materialName: 'SS Screw',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'c5c71772-c50a-41cc-8eb9-a3f68e9b962f',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '7c540707-b5e6-4a4c-902e-f21fdd8829d6',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'bae688b2-f9cc-47b2-b256-d9732214a176',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '2facb11f-f0ee-42c5-ae22-e8073efd3b48',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn40,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '736c212b-3256-4b93-acf8-425823fde5e5',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn100,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'bc4a7e10-c5ed-49b3-9374-c96f63562833',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn25,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'e671820c-66e8-49c1-a4eb-8f1505399e8a',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: 'd82fa208-2fc3-4659-ac50-6803773f95ec',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn32,
    sensorType: SensorType.wireless,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
  MaterialMasterItem(
    id: '1bd99492-9dcc-479e-baf6-d16d2cf92051',
    group: MaterialGroup.f,
    materialName: 'SS Screw 1.5inch',
    sku: '',
    unit: 'Nos',
    behaviorType: MaterialBehaviorType.fixed,
    sensorSize: SensorSize.dn50,
    sensorType: SensorType.wired,
    quantityPerSensor: 1,
    derivedFormula: null,
    formulaDivisor: null,
    variableSource: null,
    notes: 'DUMMY test value - verify before real use',
  ),
];
